# -*- coding: utf-8 -*-
"""Palindrome Checker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zWRHbz_87Rh29BWEANQAnAJQwXG9NZ_j

Level-1 Task-5 Palindrome Checker

Write a Python function that checks whether a given string is a palindrome. A palindrome is a word, phrase, or sequence that reads the
same backward as forward (e.g., "madam" or "racecar").
"""

def is_palindrome(s):
   s = s.replace(" ", "").lower()

   return s == s[::-1]

print(is_palindrome("radar"))
print(is_palindrome("A man a plan a canal Panama"))
print(is_palindrome("hello"))
print(is_palindrome("racecar"))
print(is_palindrome(""))